- name: armbian-btt_cb2-bookworm
  type: armbian
  img_download_url: "https://github.com/Lino77/armbian-builds/releases/latest/download/armbian-bigtreetech_cb2_bookworm.img.xz"
  img_hash_url: "https://github.com/Lino77/armbian-builds/releases/latest/download/armbian-bigtreetech_cb2_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 9000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    #- 20-cb2-enable-dsi
  rpi_json:
    name: "RatOS $VERSION$ - BigTreeTech CB2 (64-bit)"
    description: "A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    devices:
      - "btt_cb2-64bit"
