- name: raspberry_pi-arm64-bookworm
  type: raspberry
  img_download_url: "https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2025-10-02/2025-10-01-raspios-bookworm-arm64-lite.img.xz.torrent"
  img_hash_url: "https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2025-10-02/2025-10-01-raspios-bookworm-arm64-lite.img.xz.sha256"
  env:
    ARCH: arm64
    IMAGE_ENLARGEROOT: 9000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 84-hotspot
  rpi_json:
    name: "RatOS $VERSION$ - Raspberry Pi (64-bit)"
    description: "A port of Raspberry Pi OS with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    init_format: "systemd"
    devices:
      - "pi3-64bit"
      - "pi4-64bit"
      - "pi5-64bit"

- name: armbian-orangepi4_lts-bookworm
  type: armbian
  img_download_url: "https://github.com/mainsail-crew/armbian-builds/releases/latest/download/armbian-orangepi4_lts_bookworm.img.xz"
  img_hash_url: "https://github.com/mainsail-crew/armbian-builds/releases/latest/download/armbian-orangepi4_lts_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 9000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-opi-4lts-spi
    - 84-hotspot
  rpi_json:
    name: "RatOS $VERSION$ - Orange Pi 4 LTS (64-bit)"
    description: "A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    devices:
      - "opi4-64bit"

- name: armbian-orangepi_zero3-bookworm
  type: armbian
  img_download_url: "https://github.com/mainsail-crew/armbian-builds/releases/latest/download/armbian-orangepi_zero3_bookworm.img.xz"
  img_hash_url: "https://github.com/mainsail-crew/armbian-builds/releases/latest/download/armbian-orangepi_zero3_bookworm.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 9000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-opi-zero3
    - 84-hotspot
  rpi_json:
    name: "RatOS $VERSION$ - Orange Pi Zero3 (64-bit)"
    description: "A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    devices:
      - "opizero3-64bit"

- name: armbian-btt_cb2-bookworm
  type: armbian
  img_download_url: "https://github.com/bigtreetech/CB2/releases/download/V3.0.2/CB2_Debian12_minimal_kernel6.1_20250821.img.xz"
  img_hash_url: "https://raw.githubusercontent.com/Lino77/mainsailos/BTT_CB2/CB2_Debian12_minimal_kernel6.1_20250821.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 9000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  special_modules:
    - 20-cb2-enable-dsi
    - 84-hotspot
  rpi_json:
    name: "RatOS $VERSION$ - BigTreeTech CB2 (64-bit)"
    description: "A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    devices:
      - "btt_cb2-64bit"
