- name: armbian-btt_cb2-bookworm
  type: armbian
  img_download_url: "https://github.com/bigtreetech/CB2/releases/download/V3.0.2/CB2_Debian12_minimal_kernel6.1_20250821.img.xz"
  img_hash_url: "https://raw.githubusercontent.com/Lino77/mainsailos/BTT_CB2/CB2_Debian12_minimal_kernel6.1_20250821.img.xz.sha256"
  env:
    ARCH: arm64
    DISTRO: armbian
    IMAGE_ENLARGEROOT: 9000
    MOUNT_PROC: 1
    MOUNT_SYS: 1
  rpi_json:
    name: "RatOS $VERSION$ - BigTreeTech CB2 (64-bit)"
    description: "A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
    icon: "https://os.mainsail.xyz/rpi-imager.png"
    devices:
      - "btt_cb2-64bit"    
      
      
